server:
  port: 8802
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn_springcloud
    username: root
    password: 023017lys
  session:
    # 存储类型修改为redis
    store-type: redis
  redis:
    # Redis服务器的信息，该咋写咋写
    host: localhost
    port: 6379