server:
  port: 8801
spring:
  application:
    name: borrowservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn_springcloud
    username: root
    password: 023017lys
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: 192.168.75.1:8848
    sentinel:
      transport:
        dashboard: localhost:8858
      # 将刚刚编写的请求映射设定为限流页面
      block-page: /blocked
