server:
  port: 8701
spring:
  application:
    name: bookservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn_springcloud
    username: root
    password: 023017lys
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: 192.168.75.1:8848
    sentinel:
      transport:
        # 添加监控页面地址即可
        dashboard: localhost:8858
seata:
  service:
    vgroup-mapping:
      # 这里需要对事务组做映射，默认的分组名为 应用名称-seata-service-group，将其映射到default集群
      # 这个很关键，一定要配置对，不然会找不到服务
      bookservice-seata-service-group: default
    grouplist:
      default: localhost:8091